version: '3.4'

services:
  reviewservice:
    image: ${DOCKER_REGISTRY-}reviewservice
    build:
      context: .
      dockerfile: ReviewService/Dockerfile

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile


  roomservice:
    image: ${DOCKER_REGISTRY-}roomservice
    build:
      context: .
      dockerfile: RoomService/Dockerfile    
    environment:
        ConnectionStrings_DefaultConnection: "Host=roomdb;User ID =roomdb;Password=roomdb; Port=5432;Database=rooms;"
    depends_on:
        - roomdb
  userdb:
    image: postgres:latest
    container_name: userdb
    environment:
      POSTGRES_USER: 'userdb'
      POSTGRES_PASSWORD: 'userdb'
      POSTGRES_DB: 'users'
    ports:
      - 5431:5432

  roomdb:
    image: postgres:latest
    container_name: roomdb
    environment:
      POSTGRES_USER: 'roomdb'
      POSTGRES_PASSWORD: 'roomdb'
      POSTGRES_DB: 'rooms'
    volumes:
      - postgresdb:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
volumes:
  postgresdb:


